personal_info:
  name: "John Doe"
  email: "john.doe@email.com"
  phone: "+1 (555) 123-4567"
  location: "San Francisco, CA"
  linkedin: "linkedin.com/in/johndoe"

summary: >
  Experienced software engineer with 8 years of expertise in building scalable web applications
  and microservices. Skilled in Python, JavaScript, and cloud technologies.

work_experience:
  - company: "Tech Corp"
    position: "Senior Software Engineer"
    duration: "2020-Present"
    achievements:
      - "Led development of microservices architecture serving 1M+ daily users"
      - "Reduced system latency by 40% through optimization of database queries"
      - "Mentored 5 junior developers and implemented agile development practices"

  - company: "StartupCo"
    position: "Full Stack Developer"
    duration: "2017-2020"
    achievements:
      - "Developed and launched company's flagship product using React and Django"
      - "Implemented CI/CD pipeline reducing deployment time by 60%"
      - "Integrated third-party APIs improving user engagement by 35%"

skills:
  technical:
    - "Python (Django, Flask)"
    - "JavaScript (React, Node.js)"
    - "AWS (Lambda, EC2, S3)"
    - "Docker & Kubernetes"
    - "SQL & NoSQL Databases"
  
  soft_skills:
    - "Team Leadership"
    - "Project Management"
    - "Technical Documentation"
    - "Problem Solving"

education:
  - degree: "BS Computer Science"
    school: "University of California, Berkeley"
    year: "2016"